## Travis docs: https://docs.travis-ci.com/user/languages/julia/

language: julia
os:
  - linux
  - osx
  
julia:
  - nightly
  - 1.1
  - 1.0.3
  
matrix:
  allow_failures:
   - julia: nightly

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
      
